# Generated by Django 4.0.5 on 2022-06-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_product_id_alter_stock_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['id']},
        ),
    ]
