# Generated by Django 4.0.5 on 2022-06-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_alter_stock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
